# Generated by Django 5.2.11 on 2026-02-13 17:29

import django.db.models.deletion
import django.utils.timezone
import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GameRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        default=game.models.generate_room_code,
                        max_length=6,
                        unique=True,
                        verbose_name="Код комнаты",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Ожидание"),
                            ("playing", "Игра"),
                            ("finished", "Завершена"),
                        ],
                        default="waiting",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "current_question_index",
                    models.IntegerField(default=0, verbose_name="Текущий вопрос"),
                ),
                (
                    "question_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Вопрос начат в"
                    ),
                ),
                (
                    "host_session",
                    models.CharField(max_length=100, verbose_name="Сессия хоста"),
                ),
                (
                    "num_questions",
                    models.IntegerField(default=10, verbose_name="Кол-во вопросов"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Игровая комната",
                "verbose_name_plural": "Игровые комнаты",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=500, verbose_name="Вопрос")),
                (
                    "option_a",
                    models.CharField(max_length=200, verbose_name="Вариант A"),
                ),
                (
                    "option_b",
                    models.CharField(max_length=200, verbose_name="Вариант B"),
                ),
                (
                    "option_c",
                    models.CharField(max_length=200, verbose_name="Вариант C"),
                ),
                (
                    "option_d",
                    models.CharField(max_length=200, verbose_name="Вариант D"),
                ),
                (
                    "correct",
                    models.CharField(
                        choices=[("a", "A"), ("b", "B"), ("c", "C"), ("d", "D")],
                        max_length=1,
                        verbose_name="Правильный ответ",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=100, verbose_name="Категория"),
                ),
            ],
            options={
                "verbose_name": "Вопрос",
                "verbose_name_plural": "Вопросы",
            },
        ),
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Имя")),
                ("score", models.IntegerField(default=0, verbose_name="Очки")),
                (
                    "session_key",
                    models.CharField(max_length=100, verbose_name="Ключ сессии"),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="players",
                        to="game.gameroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игрок",
                "verbose_name_plural": "Игроки",
                "unique_together": {("room", "session_key")},
            },
        ),
        migrations.CreateModel(
            name="RoomQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(verbose_name="Порядок")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="game.question"
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_questions",
                        to="game.gameroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вопрос комнаты",
                "verbose_name_plural": "Вопросы комнаты",
                "ordering": ["order"],
                "unique_together": {("room", "order")},
            },
        ),
        migrations.CreateModel(
            name="PlayerAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.CharField(max_length=1, verbose_name="Ответ")),
                ("is_correct", models.BooleanField(verbose_name="Правильно")),
                ("points", models.IntegerField(default=0, verbose_name="Очки")),
                (
                    "answered_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Время ответа"
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="game.player",
                    ),
                ),
                (
                    "room_question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_answers",
                        to="game.roomquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ игрока",
                "verbose_name_plural": "Ответы игроков",
                "unique_together": {("player", "room_question")},
            },
        ),
    ]
