# Generated by Django 5.2.8 on 2026-03-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "slug",
                    models.SlugField(
                        max_length=100, unique=True, verbose_name="URL-идентификатор"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Аббревиатура"
                    ),
                ),
                ("description", models.TextField(verbose_name="Краткое описание")),
                (
                    "full_description",
                    models.TextField(blank=True, verbose_name="Полное описание"),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="CSS-класс иконки (Bootstrap Icons)",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок отображения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория оборудования",
                "verbose_name_plural": "Категории оборудования",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="ContactRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Имя")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "phone",
                    models.CharField(blank=True, max_length=30, verbose_name="Телефон"),
                ),
                ("message", models.TextField(verbose_name="Сообщение")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "Заявка",
                "verbose_name_plural": "Заявки",
                "ordering": ["-created_at"],
            },
        ),
    ]
