# Generated by Django 5.2.8 on 2026-07-10 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("prompt", models.CharField(blank=True, max_length=255)),
                ("credits_used", models.IntegerField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, max_length=128)),
            ],
            options={
                "verbose_name": "генерация",
                "verbose_name_plural": "генерации",
            },
        ),
    ]
